import prettier from 'eslint-config-prettier'
import withNuxt from './.nuxt/eslint.config.mjs'

export default withNuxt(
    // Generated by `wrangler types`
    { ignores: ['worker/worker-configuration.d.ts', '.wrangler/**'] },
    prettier,
    {
        rules: {
            'vue/component-name-in-template-casing': ['error', 'PascalCase'],
            'vue/multi-word-component-names': 'off',
        },
    },
)
